"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from abc import (
    ABCMeta,
    abstractmethod,
)
from apis.dm_api_search.search_pb2 import (
    SearchRequest,
    SearchResponse,
)
from collections.abc import (
    AsyncIterator,
    Awaitable,
    Iterator,
)
from grpc import (
    Channel,
    Server,
    ServicerContext,
    UnaryUnaryMultiCallable,
)
from grpc.aio import (
    Channel,
    Server,
    ServicerContext,
    UnaryUnaryMultiCallable,
)
from typing import (
    TypeVar,
    Union,
)

_T = TypeVar('_T')

class _MaybeAsyncIterator(AsyncIterator[_T], Iterator[_T], metaclass=ABCMeta):
    ...

class _ServicerContext(ServicerContext, ServicerContext):  # type: ignore
    ...

class SearchEngineStub:
    def __init__(self, channel: Union[Channel, Channel]) -> None: ...
    Search: UnaryUnaryMultiCallable[
        SearchRequest,
        SearchResponse,
    ]

class SearchEngineAsyncStub:
    Search: UnaryUnaryMultiCallable[
        SearchRequest,
        SearchResponse,
    ]

class SearchEngineServicer(metaclass=ABCMeta):
    @abstractmethod
    def Search(
        self,
        request: SearchRequest,
        context: _ServicerContext,
    ) -> Union[SearchResponse, Awaitable[SearchResponse]]: ...

def add_SearchEngineServicer_to_server(servicer: SearchEngineServicer, server: Union[Server, Server]) -> None: ...
